apiVersion: apps/v1
kind: Deployment
metadata:
  name: person-service
spec:
  template:
    spec:
      containers:
      - name: person-service
        livenessProbe:
          httpGet:
            path: /q/health/live
            port: 8080
            scheme: HTTP
          timeoutSeconds: 2
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3