apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: builder-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
